In [1]:
%matplotlib inline
import numpy as np
import matplotlib.pyplot as plt

In [2]:
p=[999,1099,1199]

In [3]:
c=30.2

In [4]:
prices=np.array(p)

In [5]:
prices

array([ 999, 1099, 1199])

In [6]:
print(prices)

[ 999 1099 1199]


In [7]:
prices*c

array([30169.8, 33189.8, 36209.8])