In [1]:
%matplotlib inline
import numpy as np
import matplotlib.pyplot as plt

In [2]:
A=np.random.randn(100)

In [3]:
A

array([-1.59026139, -0.61851405, -0.31984852, -0.12352132, -0.61152796,
       -0.79742884, -0.42390453, -0.71307149,  0.49966252,  1.30570797,
        0.17598969, -1.14480174,  0.99758179, -0.68971084,  0.3694019 ,
        0.87295519,  0.00697159,  0.2026995 , -0.32991267, -0.88399056,
       -0.40025687, -1.54510666, -1.221198  , -0.33766454, -0.42485335,
        0.71299913, -0.13046849, -1.04778561, -1.21953455,  0.59913422,
        0.05420236,  0.49466522,  0.03870887,  0.85040323, -0.94845892,
        0.98205668, -0.28689435,  0.63020732, -1.37187519, -1.1605312 ,
        1.77710969, -1.71988616,  0.35808579, -0.11075809,  1.03666282,
       -0.40479085, -0.63952477, -0.30463113, -0.54075424, -0.46230933,
        0.45528174, -0.4323971 , -0.91617189, -0.77408116, -0.36130939,
        0.65466566,  0.01421593,  2.1758387 , -1.00085209,  2.80547279,
        0.43390353, -1.51863488,  0.1364357 ,  0.11230352, -1.24382501,
        0.00860406, -0.31649144, -0.0913652 ,  0.0725858 ,  0.45

In [4]:
A=A*10+50

In [5]:
A

array([34.09738611, 43.81485946, 46.80151476, 48.76478679, 43.88472036,
       42.02571156, 45.76095474, 42.86928514, 54.99662523, 63.05707971,
       51.75989692, 38.55198263, 59.97581792, 43.10289158, 53.69401898,
       58.72955186, 50.0697159 , 52.02699505, 46.7008733 , 41.16009442,
       45.99743135, 34.54893339, 37.78801996, 46.62335463, 45.75146647,
       57.12999135, 48.69531515, 39.52214393, 37.80465455, 55.99134215,
       50.54202363, 54.94665217, 50.38708866, 58.50403232, 40.5154108 ,
       59.82056677, 47.13105654, 56.3020732 , 36.28124812, 38.39468796,
       67.77109692, 32.80113837, 53.58085789, 48.89241912, 60.36662818,
       45.95209148, 43.60475227, 46.95368868, 44.59245756, 45.37690672,
       54.55281744, 45.67602903, 40.83828105, 42.25918836, 46.38690607,
       56.54665661, 50.14215927, 71.75838702, 39.9914791 , 78.0547279 ,
       54.33903533, 34.8136512 , 51.36435704, 51.12303525, 37.5617499 ,
       50.08604058, 46.83508565, 49.086348  , 50.72585797, 54.54

In [6]:
A.shape

(100,)

In [7]:
A.shape=(5,20)

In [8]:
A

array([[34.09738611, 43.81485946, 46.80151476, 48.76478679, 43.88472036,
        42.02571156, 45.76095474, 42.86928514, 54.99662523, 63.05707971,
        51.75989692, 38.55198263, 59.97581792, 43.10289158, 53.69401898,
        58.72955186, 50.0697159 , 52.02699505, 46.7008733 , 41.16009442],
       [45.99743135, 34.54893339, 37.78801996, 46.62335463, 45.75146647,
        57.12999135, 48.69531515, 39.52214393, 37.80465455, 55.99134215,
        50.54202363, 54.94665217, 50.38708866, 58.50403232, 40.5154108 ,
        59.82056677, 47.13105654, 56.3020732 , 36.28124812, 38.39468796],
       [67.77109692, 32.80113837, 53.58085789, 48.89241912, 60.36662818,
        45.95209148, 43.60475227, 46.95368868, 44.59245756, 45.37690672,
        54.55281744, 45.67602903, 40.83828105, 42.25918836, 46.38690607,
        56.54665661, 50.14215927, 71.75838702, 39.9914791 , 78.0547279 ],
       [54.33903533, 34.8136512 , 51.36435704, 51.12303525, 37.5617499 ,
        50.08604058, 46.83508565, 49.086348  , 5

In [9]:
A.reshape(100,1)

array([[34.09738611],
       [43.81485946],
       [46.80151476],
       [48.76478679],
       [43.88472036],
       [42.02571156],
       [45.76095474],
       [42.86928514],
       [54.99662523],
       [63.05707971],
       [51.75989692],
       [38.55198263],
       [59.97581792],
       [43.10289158],
       [53.69401898],
       [58.72955186],
       [50.0697159 ],
       [52.02699505],
       [46.7008733 ],
       [41.16009442],
       [45.99743135],
       [34.54893339],
       [37.78801996],
       [46.62335463],
       [45.75146647],
       [57.12999135],
       [48.69531515],
       [39.52214393],
       [37.80465455],
       [55.99134215],
       [50.54202363],
       [54.94665217],
       [50.38708866],
       [58.50403232],
       [40.5154108 ],
       [59.82056677],
       [47.13105654],
       [56.3020732 ],
       [36.28124812],
       [38.39468796],
       [67.77109692],
       [32.80113837],
       [53.58085789],
       [48.89241912],
       [60.36662818],
       [45

In [10]:
A

array([[34.09738611, 43.81485946, 46.80151476, 48.76478679, 43.88472036,
        42.02571156, 45.76095474, 42.86928514, 54.99662523, 63.05707971,
        51.75989692, 38.55198263, 59.97581792, 43.10289158, 53.69401898,
        58.72955186, 50.0697159 , 52.02699505, 46.7008733 , 41.16009442],
       [45.99743135, 34.54893339, 37.78801996, 46.62335463, 45.75146647,
        57.12999135, 48.69531515, 39.52214393, 37.80465455, 55.99134215,
        50.54202363, 54.94665217, 50.38708866, 58.50403232, 40.5154108 ,
        59.82056677, 47.13105654, 56.3020732 , 36.28124812, 38.39468796],
       [67.77109692, 32.80113837, 53.58085789, 48.89241912, 60.36662818,
        45.95209148, 43.60475227, 46.95368868, 44.59245756, 45.37690672,
        54.55281744, 45.67602903, 40.83828105, 42.25918836, 46.38690607,
        56.54665661, 50.14215927, 71.75838702, 39.9914791 , 78.0547279 ],
       [54.33903533, 34.8136512 , 51.36435704, 51.12303525, 37.5617499 ,
        50.08604058, 46.83508565, 49.086348  , 5

In [11]:
A=A.reshape(100,1)

In [12]:
A

array([[34.09738611],
       [43.81485946],
       [46.80151476],
       [48.76478679],
       [43.88472036],
       [42.02571156],
       [45.76095474],
       [42.86928514],
       [54.99662523],
       [63.05707971],
       [51.75989692],
       [38.55198263],
       [59.97581792],
       [43.10289158],
       [53.69401898],
       [58.72955186],
       [50.0697159 ],
       [52.02699505],
       [46.7008733 ],
       [41.16009442],
       [45.99743135],
       [34.54893339],
       [37.78801996],
       [46.62335463],
       [45.75146647],
       [57.12999135],
       [48.69531515],
       [39.52214393],
       [37.80465455],
       [55.99134215],
       [50.54202363],
       [54.94665217],
       [50.38708866],
       [58.50403232],
       [40.5154108 ],
       [59.82056677],
       [47.13105654],
       [56.3020732 ],
       [36.28124812],
       [38.39468796],
       [67.77109692],
       [32.80113837],
       [53.58085789],
       [48.89241912],
       [60.36662818],
       [45