In [1]:
%matplotlib inline
import numpy as np
import matplotlib.pyplot as plt

In [3]:
x=np.array([[-3,2],[-6,5],[3,-4],[2,-8]])
y=np.array([1,1,2,2])

In [4]:
from sklearn.svm import SVC

In [5]:
clf=SVC()

In [11]:
clf.fit(x,y)

C:\Users\user\Anaconda3\lib\site-packages\sklearn\svm\base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
    kernel='rbf', max_iter=-1, probability=False, random_state=None,
    shrinking=True, tol=0.001, verbose=False)

In [8]:
clf.predict([[-3,2]])

array([1])

In [9]:
clf.predict(x)

array([1, 1, 2, 2])

In [10]:
clf.predict([[2,4]])

array([1])